services:
  api:
    build: .
    ports:
      - "6179:6179"
    environment:
      SSL_CERT: "/certs/localhost.crt"
      SSL_KEY: "/certs/localhost.key"
      MONGO_IP: "mongo"
  mongo:
    image: "mongo:4.4.17"
    environment:
      - AUTH=no
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo-data:
