FROM node:latest

RUN apt update 
RUN apt install -y git
RUN mkdir /certs
ADD ./certs/ /certs
RUN mkdir /src 
RUN git clone https://github.com/robertwilkinson9/ts-reserve-assets.git /src/ts-reserve-assets
RUN git clone https://github.com/robertwilkinson9/ts-REST-api-for-mongodb.git /src/ts-REST-api-for-mongodb
RUN mkdir /src/ts-REST-api-for-mongodb/config
WORKDIR /src/ts-REST-api-for-mongodb
RUN npm install
CMD ["npm", "run", "book"]
