#!/bin/bash
if [ $# -ne 1 ]
then
	echo "NEED 1 argument - type e.g. book, desk"
	exit 1
fi
TYPE=$1

URL=$(minikube service mongodb --url | sed -e 's/^http:\/\///')
echo -n "  ${TYPE}_connection_string: " 
echo $(echo "mongodb://${TYPE}1:1${TYPE}@${URL}/${TYPE}" | base64)
