#!/bin/bash
if [ $# -ne 1 ]
then
	echo "NEED 1 argument - type e.g. book, desk"
	exit 1
fi
TYPE=$1

echo -n "  ${TYPE}_connection_string: " 
echo $(echo "mongodb://reserver:assets@mongodb.default.svc.cluster.local/${TYPE}" | base64 -w 100)
