#!/bin/bash
if [ $# -ne 1 ]
then
	echo "NEED 1 argument - type e.g. book, desk"
	exit 1
fi
TYPE=$1

URL=$(minikube service mongodb --url | sed -e 's/^http:\/\///')
echo -n "  ${TYPE}_connection_string: " 
#echo $(echo "mongodb://${TYPE}1:1${TYPE}@${URL}/${TYPE}" | base64)
echo $(echo "mongodb://reserver:assets@${URL}/${TYPE}" | base64)
# e.g. mongodb://reserver:assets@192.168.49.2:31572/book
