apiVersion: v1
kind: Service
metadata:
  name: book-backend-service
spec:
  selector:
    app: book-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 6180
      targetPort: 6180
      nodePort: 31000
