---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: book-backend
  name: book-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-backend
  strategy: {}
  template:
    metadata:
      labels:
        app: book-backend
    spec:
      containers:
      - name: book-backend
        image: book-backend:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 6180
        env:
        - name: SSL_CERT
          value: /certs/localhost.crt
        - name: SSL_KEY
          value: /certs/localhost.key
        - name: MONGO_IP
          value: mongodb.default.svc.cluster.local
        - name: DB_NAME
          value: book
        - name: DB_USER
          value: reserver
        - name: DB_PASSWORD
          value: assets
        - name: API_PORT
          value: "6180"
        - name: CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: mongodb-connection-strings
              key: book_connection_string
