---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: desk-backend
  name: desk-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desk-backend
  strategy: {}
  template:
    metadata:
      labels:
        app: desk-backend
    spec:
      containers:
      - name: desk-backend
        image: robertwilkinsonwork299/reserve-assets-desk-backend
        ports:
          - containerPort: 6179
        env:
        - name: SSL_CERT
          value: /certs/localhost.crt
        - name: SSL_KEY
          value: /certs/localhost.key
        - name: MONGO_IP
          value: my-mongodb.default.svc.cluster.local
        - name: DB_NAME
          value: desk
        - name: DB_USER
          value: reserver
        - name: DB_PASSWORD
          value: assets
        - name: API_PORT
          value: "6179"
        - name: CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: mongodb-connection-strings
              key: desk_connection_string
